# Generated by Django 4.2.6 on 2023-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_comment_published_comment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, default='general', null=True, related_name='tags', to='blogging.tag', verbose_name='Tags'),
        ),
    ]
