# Generated by Django 4.2.6 on 2023-10-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
